<?xml version="1.0" encoding="utf-8"?><Database Name="PROJDB" Class="projetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost\SQLEXPRESS2017;Initial Catalog=PROJDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProjDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.alarmes" Member="alarmes">
    <Type Name="alarme">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="stationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="state" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="station_alarme" Member="station" ThisKey="stationID" OtherKey="id" Type="station" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.stations" Member="stations">
    <Type Name="station">
      <Column Name="adresse" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="x" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="y" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="etat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pay" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="contact" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="respCIN" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="connexion" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="tnkNbr" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="station_alarme" Member="alarmes" ThisKey="id" OtherKey="stationID" Type="alarme" />
      <Association Name="station_alimentation" Member="alimentations" ThisKey="id" OtherKey="stationID" Type="alimentation" />
      <Association Name="station_reservoir" Member="reservoirs" ThisKey="id" OtherKey="stationID" Type="reservoir" />
      <Association Name="station_SiteStation" Member="SiteStations" ThisKey="id" OtherKey="stationID" Type="SiteStation" />
      <Association Name="pay_station" Member="pay1" ThisKey="pay" OtherKey="name" Type="pay" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="responsable_station" Member="responsable" ThisKey="respCIN" OtherKey="cin" Type="responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.alimentations" Member="alimentations">
    <Type Name="alimentation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chauffeur" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="camion" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="produitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="qte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="siteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="responsable" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="sent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="station_alimentation" Member="station" ThisKey="stationID" OtherKey="id" Type="station" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="produit_alimentation" Member="produit" ThisKey="produitID" OtherKey="id" Type="produit" IsForeignKey="true" />
      <Association Name="site_alimentation" Member="site" ThisKey="siteID" OtherKey="id" Type="site" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.barémage" Member="barémages">
    <Type Name="barémage">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="reservoirID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vol20" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol19" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol18" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol17" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol16" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol15" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol14" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol13" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vol1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="reservoir_barémage" Member="reservoir" ThisKey="reservoirID" OtherKey="id" Type="reservoir" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.data" Member="datas">
    <Type Name="data">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="taille" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="nbr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="signalForce" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="PSW" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="newAlert" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mouvReservoir" Member="mouvReservoirs">
    <Type Name="mouvReservoir">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="reservoirID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="niveau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="reservoir_mouvReservoir" Member="reservoir" ThisKey="reservoirID" OtherKey="id" Type="reservoir" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.pays" Member="pays">
    <Type Name="pay">
      <Column Name="name" Type="System.String" DbType="NChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="flag" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="map" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="pay_station" Member="stations" ThisKey="name" OtherKey="pay" Type="station" />
      <Association Name="pay_site" Member="sites" ThisKey="name" OtherKey="pay" Type="site" />
    </Type>
  </Table>
  <Table Name="dbo.produits" Member="produits">
    <Type Name="produit">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ref" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="produit_alimentation" Member="alimentations" ThisKey="id" OtherKey="produitID" Type="alimentation" />
      <Association Name="produit_remplissage" Member="remplissages" ThisKey="id" OtherKey="productID" Type="remplissage" />
      <Association Name="produit_reservoir" Member="reservoirs" ThisKey="id" OtherKey="productID" Type="reservoir" />
      <Association Name="produit_SiteProduit" Member="SiteProduits" ThisKey="id" OtherKey="produitID" Type="SiteProduit" />
    </Type>
  </Table>
  <Table Name="dbo.remplissage" Member="remplissages">
    <Type Name="remplissage">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="qte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="siteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="productID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="responsable" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="produit_remplissage" Member="produit" ThisKey="productID" OtherKey="id" Type="produit" IsForeignKey="true" />
      <Association Name="site_remplissage" Member="site" ThisKey="siteID" OtherKey="id" Type="site" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.reservoirs" Member="reservoirs">
    <Type Name="reservoir">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="min" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="max" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="productID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="liter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="niveau" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="reservoir_barémage" Member="barémages" ThisKey="id" OtherKey="reservoirID" Type="barémage" />
      <Association Name="reservoir_mouvReservoir" Member="mouvReservoirs" ThisKey="id" OtherKey="reservoirID" Type="mouvReservoir" />
      <Association Name="produit_reservoir" Member="produit" ThisKey="productID" OtherKey="id" Type="produit" IsForeignKey="true" />
      <Association Name="station_reservoir" Member="station" ThisKey="stationID" OtherKey="id" Type="station" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.responsables" Member="responsables">
    <Type Name="responsable">
      <Column Name="cin" Type="System.String" DbType="NChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="responsable_station" Member="stations" ThisKey="cin" OtherKey="respCIN" Type="station" />
    </Type>
  </Table>
  <Table Name="dbo.SiteProduit" Member="SiteProduits">
    <Type Name="SiteProduit">
      <Column Name="siteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="produitID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="produit_SiteProduit" Member="produit" ThisKey="produitID" OtherKey="id" Type="produit" IsForeignKey="true" />
      <Association Name="site_SiteProduit" Member="site" ThisKey="siteID" OtherKey="id" Type="site" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sites" Member="sites">
    <Type Name="site">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="reservoir" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="adr" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="contact" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="pay" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="site_alimentation" Member="alimentations" ThisKey="id" OtherKey="siteID" Type="alimentation" />
      <Association Name="site_remplissage" Member="remplissages" ThisKey="id" OtherKey="siteID" Type="remplissage" />
      <Association Name="site_SiteProduit" Member="SiteProduits" ThisKey="id" OtherKey="siteID" Type="SiteProduit" />
      <Association Name="site_SiteStation" Member="SiteStations" ThisKey="id" OtherKey="siteID" Type="SiteStation" />
      <Association Name="pay_site" Member="pay1" ThisKey="pay" OtherKey="name" Type="pay" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.SiteStation" Member="SiteStations">
    <Type Name="SiteStation">
      <Column Name="siteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="site_SiteStation" Member="site" ThisKey="siteID" OtherKey="id" Type="site" IsForeignKey="true" />
      <Association Name="station_SiteStation" Member="station" ThisKey="stationID" OtherKey="id" Type="station" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>